Work around javac method reference bug
javac fails to compile this method reference:
packages/apps/DocumentsUI/src/com/android/documentsui/BaseActivity.java:308: error: incompatible types: invalid method reference
                    mInjector.actions::openContainerDocument)
                    ^
    openContainerDocument(DocumentInfo) in ActionHandler is defined in an inaccessible class or interface

This is a symptom of https://bugs.openjdk.java.net/browse/JDK-8073842
fixed in JDK9.  Use the equivalent lambda instead for now.

Test: m -j ANDROID_FORCE_JACK_ENABLED=disabled
Change-Id: Id68f48d3896fc239a8e77ffad209547184a8290e