Don't statically include DocumentsUI-lib in tests
DocumentsUI-libs shouldn't be included in tests, tests get those
classes via the app they are instrumenting.  Including DocumentsUI-libs
causes androidx.startup to be included in both the app and the tests,
which then causes failures when starting the tests due to resource
conflicts:

Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f12001e
java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: android.content.res.Resources$NotFoundException: String resource ID #0x7f12001e

Bug: 328639759
Test: atest DocumentsUIGoogleTests
Flag: TEST_ONLY
Change-Id: I05ba39a0fe51a455da95b6497ef2cb1243ea615f