Commit SearchFragment-dismissing transaction safely
Schedule (self-)dissmissing SearchFragment with using a variation of
FragmentTransaction.commit() method, instead of trying to execute
transaction right away using commitNow() with may cause
java.lang.IllegalStateException: "FragmentManager is already executing
transactions".

Bug: 259640896
Test: atest DocumentsUIGoogleTests
Change-Id: Ia1d29104e4ada298b4fc02b4cec98a892ecbd3f6